name: Deploy Expo Web to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install -g expo-cli
          npm install
          
      - name: Build Expo Web
        run: |
          expo build:web
          
      - name: Configure Jekyll to serve Expo Web
        run: |
          # Crie um arquivo de configuração Jekyll básico
          echo 'theme: jekyll-theme-minimal' > _config.yml
          echo 'exclude: [node_modules]' >> _config.yml
          
          # Mova a build do Expo para o diretório que o Jekyll servirá
          mv web-build/ _site/
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Build Expo Web
        run: |
          # Instala o polyfill necessário
          npm install crypto-browserify
          # Configura variáveis de ambiente para o Webpack
          export NODE_OPTIONS=--openssl-legacy-provider
          # Gera a build com configuração customizada
          expo build:web --no-pwa

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
